### PR TITLE
fix(dependencies): Update Hapi peer dependency to reflect reality.

### PR DESCRIPTION
**Pull request by nyergler**
The current `master` branch supports up to (but not including) Hapi 17.

### CODE REVIEW

**Comment by sjl2** [comment]
nit: can you change the PR title to the format required by [`generate-changelog`](https://github.com/lob/generate-changelog#usage)?

While we aren't using it any more for our convox apps, it is still in use for our modules.

**Comment by sjl2** [comment]
Interesting, any idea while Circle is trying to build this public repo?

**Review by sjl2 — APPROVED** [review]
LGTM

**Comment by nyergler** [comment]
@sjl2 I recall @robinjoseph08 mentioning that we accidentally added the circle hook at _all_ our repos at one point; I've removed it from this one.

**Review by marklee22 — APPROVED** [review]

**Pull request merged**
